### ISSUE TITLE
Step 4 doesn't work `Error: Cannot enqueue Query after fatal error.`

### ISSUE THREAD

**Issue by That-David-Guy** [dwmkerr/node-docker-microservice#7]
Hi

Really good tutorial, but sadly I can't get the final step with docker-composer to work.

I've also tried pulling your repo and running that but I seem to get the same error from the `users-service`

```
Error: An error occured getting the users: Error: Cannot enqueue Query after fatal error.
```

It works if I run each container separately.

I also ran into this issue in step 2 if it matters: #4 . I don't know how to fix it in docker-file though as I don't know where to put the `sleep`

Any help would be fantastic.

Cheers

I'm on a macbook air using Docker for Mac

**Comment by kitgary** [comment]
I modified the docker-compose file as follows.

<pre>
<code>
version: '2'
services:
  users-service:
    build:
      ./users-service
    container_name: users_service
    command: bash -c "sleep 10; node /app/index.js"
    ports:
      - 8123:8123
    links:
      - db:db
    environment:
      - DATABASE_HOST=db
  db:
    build: ./test-database
    container_name: db
    ports:
      - 3306:3306
</code>
</pre>

I added the command for sleep 10 seconds to wait for the mysql database start up. And also I need to add the container_name, otherwise the mysql container cannot be linked to the users-service properly.

Cheers

**Comment by That-David-Guy** [comment]
Thanks. Works!

So I assume the problem was that user-service starts before the db had actually finished?

I also notice you removed `depends_on`, does `links` replace it?

I'll close the issue
